#+TITLE:     Preserving software: ensuring availability and traceability
#+AUTHOR:    Roberto Di Cosmo, Arnaud Legrand
#+DATE: November 8, 2016
#+STARTUP: overview indent

*This seminar took place on November 8, 2016 @ 1:30PM-4:30PM (UTC+1). The
link to the video is below.*

* Table of Contents                                                     :TOC:
- [[#practical-information][Practical Information]]
  - [[#webcastvideo][Webcast/Video]]
  - [[#persons-in-charge][Persons in charge]]
  - [[#locations][Locations]]
- [[#practical-session-requirements][Practical Session Requirements]]

* Practical Information

The first step towards reproducibility of experiments based on
software is to be able to actually find the software that was used in
the experiment. While this seems to be self evident, in practice it
turns out to be not easy at all, and the tools which are commonly used
today have severe limitations.

In this talk, Roberto Di Cosmo will provide an overview of the issues
we face when trying to ensure that digital content in general, and
software in particular, is properly available and traceable.  In order
to address these issues, the [[https://www.softwareheritage.org/][Software Heritage]] initiative was started
at Inria, and we will report here on its progress.

** Webcast/Video
Here is the *[[https://gricad.univ-grenoble-alpes.fr/video/preserving-software-ensuring-availability-and-traceability][link to the video]]*. If you have any trouble with the
flashplayer, here is a *[[http://newstream.u-ga.fr/2016-11-08_Reproducible-Research_Roberto-Di-Cosmo.mp4][direct link to the mpeg4 video]]*. 

#+BEGIN_CENTER
[[https://gricad.univ-grenoble-alpes.fr/video/preserving-software-ensuring-availability-and-traceability][file:video_thn.png]]
#+END_CENTER

The slides can be found [[file:2016-11-09-grenoble-rdicosmo-reproductibility-preserving-software.pdf][here]] (or [[https://annex.softwareheritage.org/public/talks/2016/2016-11-08-grenoble-rdicosmo-reproductibility-preserving-software.pdf][here]]).

To interact during the presentation (questions, comments), *we used
this [[https://pad.inria.fr/p/BQnJjEIwADQpPM1Q][pad]]* that we will [[file:pad.org][keep for the record]].
** Persons in charge
   - Grenoble: Arnaud Legrand
   - Bordeaux: Luka Stanisic
   - Rennes: Martin Quinson
   - Besançon: Louis-Claude Canon
** Locations
   - Grenoble: [[https://www.google.fr/maps/place/45%25C2%25B011'26.5%2522N+5%25C2%25B046'02.6%2522E/@45.1907069,5.7668488,19z/data=!3m1!4b1!4m5!3m4!1s0x0:0x0!8m2!3d45.190706!4d5.767396][Imag Amphitheater]] on Campus
* Practical Session Requirements
None.
