#+TITLE:     Numerical Reproducibility
#+AUTHOR:    Nathalie Revol, Philippe Langlois, Stef Graillat
#+DATE: May 3, 2016
#+STARTUP: overview indent

*This seminar will take place on May 3, 2016 @ 1:30PM-4:30PM
(UTC+2). The link to the video is below.*

* Table of Contents                                                     :TOC:
 - [[#practical-information][Practical information]]
     - [[#webcastvideo][Webcast/Video]]
     - [[#persons-in-charge][Persons in charge]]
     - [[#locations][Locations]]
 - [[#practical-session][Practical Session]]

* Practical information
Nathalie Revol, Philippe Langlois and Stef Graillat will present the
main challenges encountered when trying to achieve numerical
reproducibility and will present recent research work on this topic.
** Webcast/Video
The screencast is *[[https://mi2s.imag.fr/pm/direct][here]]* and some rooms where the audience will gather
are listed [[*Locations][below]].

To interact during the presentation (questions, comments), *we wille
use this [[https://pad.inria.fr/p/bjKfNEcD7SCvHjHF][pad]]* that we will keep for the record.
** Persons in charge
   - Grenoble: Arnaud Legrand, Frédéric Desprez, Pierre Neyron
   - Bordeaux: Luka Stanisic, Emmanuel Agullo, Nicolas P. Rougier,
     Ludovic Courtès, ...
   - Rennes: Martin Quinson
   - Besançon: Louis-Claude Canon
** Locations
   - Grenoble: [[https://goo.gl/maps/ndus7ukqfEM2][Inria]] in the large amphitheater (Arnaud Legrand)
   - Besançon:
   - Lyon:
   - Bordeaux:
   - Rennes: 
   - Paris:
   - ...
* Practical Session
To be announced. It's not clear yet whether a practical session is
adequate for this topic or not.
