#+TITLE:     Enabling open and reproducible research at computer systems' conferences: good, bad and ugly
#+AUTHOR:    Grigori Fursin
#+DATE: March 14, 2017
#+STARTUP: overview indent

*This seminar took place on March 14, 2017 @ 1:30PM-4:30PM (UTC+1). The
link to the video is below.*

* Table of Contents                                                     :TOC:
 - [[#practical-information][Practical Information]]
     - [[#webcastvideo][Webcast/Video]]
     - [[#persons-in-charge][Persons in charge]]
     - [[#locations][Locations]]
 - [[#practical-session-requirements][Practical Session Requirements]]

* Practical Information
This talk will be given by [[http://fursin.net/research.html][Grigori Fursin]].

In computer science (but also in computational science), research
claims are often based on digital artifacts (computer programs along
with their environment, data sets and meta information). Allowing
reviewers to evaluate such artifacts and others researchers to inspect
and possibly reuse such artifacts is essential to improve both the
faith in research claims and the capability to build on previous work.

In this talk, Grigori Fursin will present his experience with Artifact
Evaluation at computer systems' conferences. He will expose
encountered problems, solutions, future initiatives and supporting
frameworks.

** Webcast/Video
Here is the *[[https://gricad.univ-grenoble-alpes.fr/video/enabling-open-and-reproducible-research-computer-systems-conferences-good-bad-and-ugly][link to the video]]*. If you have any trouble with the
flashplayer, here is a *[[http://newstream.imag.fr/2017-03-14_Reproducible-Research_Grigori-Fursin.mp4][direct link to the mpeg4 video]]*. Here are the
*[[file:presentation.pdf][slides]]* used by Grigori during his talk.

#+BEGIN_CENTER
[[https://gricad.univ-grenoble-alpes.fr/video/enabling-open-and-reproducible-research-computer-systems-conferences-good-bad-and-ugly][file:video_thn.png]]
#+END_CENTER

To interact during the presentation (questions, comments), *we 
used this [[https://pad.inria.fr/p/3NkV4zwignZjRmwq][pad]]* that we will keep for the record.
** Persons in charge
   - Grenoble: Arnaud Legrand
   - Bordeaux: Luka Stanisic
   - Rennes: Martin Quinson
   - Besançon: Louis-Claude Canon
** Locations
   - Grenoble: [[https://www.google.fr/maps/place/45%25C2%25B011'26.5%2522N+5%25C2%25B046'02.6%2522E/@45.1907069,5.7668488,19z/data=!3m1!4b1!4m5!3m4!1s0x0:0x0!8m2!3d45.190706!4d5.767396][Imag Amphitheater]] on Campus
* Practical Session Requirements
None
