#+TITLE:     Introduction, producing replicable articles and managing a laboratory notebook with emacs/org-mode
#+AUTHOR:    Arnaud Legrand
#+DATE: March 7, 2016
#+STARTUP: overview indent


*This page is under construction, so please check it regularly, especially a few days before the webinar to [[file:index.org#practical-session-requirements][install the software required in the practical session]].*

* Table of Contents                                                     :TOC:
 - [[#practical-information][Practical information]]
     - [[#webcast][Webcast]]
     - [[#persons-in-charge][Persons in charge]]
     - [[#locations][Locations]]
 - [[#keynote][Keynote]]
 - [[#practical-session-requirements][Practical Session Requirements]]
     - [[#installing-emacs-ess-auctex-][Installing emacs, ess, auctex, ...]]
     - [[#a-stub-of-replicable-article][A stub of replicable article]]
     - [[#reproducible-research-emacs-configuration-for-maintaining-your-laboratory-notebook][Reproducible research emacs configuration for maintaining your laboratory notebook]]

* Practical information
** Webcast
   - To follow this webinar in real time, please go to the
     [[https://mi2s.imag.fr/pm/direct][Screencast]]. From what we know, you mostly need javascript to be
     activated for this to work. You can check on this [[https://mi2s.imag.fr/pm/videos-en-ligne][page]] whether
     you manage to see some other videos. If so, you should be fine. 
   - To interact during the presentation, the easier will be to have
     use this [[https://pad.inria.fr/p/9mSyf4BhzZ9soDE9][pad]]. Write your questions, comments here and we'll try
     to address them during the presentation. If they cannot be
     addressed, leave them and we'll try to answer them later in some
     kind of FAQ section.
   - Video archive (soon)
** Persons in charge
   - Grenoble: Arnaud Legrand, Frédéric Desprez
   - Bordeaux: Luka Stanisic, Emmanuel Agullo, Nicolas P. Rougier,
     Ludovic Courtès
   - Rennes: Martin Quinson
** Locations
   - Grenoble: [[https://www.google.com/maps/d/u/0/viewer?mid=zYJixSyqUx3w.kZRnKm__28GY&hl=fr][MJK]] (Arnaud Legrand), GIANT (Frédéric Desprez), Inria A103 (Pierre Neyron), ...
   - Lyon: 
   - Bordeaux: Ada Lovelace room (Ludovic Courtès)
   - Rennes: salle visio Bréhat (Martin Quinson)
   - ...
* Keynote
  [[https://team.inria.fr/polaris/members/arnaud-legrand/][Arnaud Legrand]] will provide a [[https://github.com/alegrand/SMPE/raw/master/lectures/talk_16_02_03_Grenoble_G5K.pdf][general introduction on reproducible
  research]].
* Practical Session Requirements
  We will explain the audience how to create and manage replicable
  articles and give advice on how to manage a laboratory notebook on a
  daily basis.

  To benefit from this presentation, we recommand the audience to
  install the software described in each section. In particular, we
  want a recent version of emacs with ESS (for R) and AucTeX (for
  LaTeX). Finally, *you will need a working LaTeX environment to build
  a replicable article*.
  #+BEGIN_CENTER
  *Once you're done with the software installation that are specific to
  your operating system, go to this [[*Reproducible research emacs configuration][section]]*.
  #+END_CENTER
** Installing emacs, ess, auctex, ...
*** Mac OsX
- *Option 1*: If you already use =brew=, simply do the following
  #+begin_src sh :results output :exports both
  brew update
  brew install emacs [--with-cocoa]
  brew linkapps emacs
  brew tap homebrew/science
  brew install ess
  brew install auctex # The name may be slightly more complicated here
  brew install wget
  #+end_src
- *Option 2*: Install the =.dmg= file from
  http://vgoulet.act.ulaval.ca/en/emacs/mac/. In that case you may
  have several versions of emacs installed on your machine and
  launching emacs from a terminal may not run the one you just
  installed. If anyone know how to get rid of this...
*** Windows
Install the =.exe= file from
http://vgoulet.act.ulaval.ca/emacs/windows/.
*** Linux
If you're running a debian system, simply do (as root):
#+begin_src sh :results output :exports both
apt-get update
apt-get install emacs org-mode ess r-base auctex
#+end_src

Then make sure you have a sufficiently recent version
#+begin_src sh :results output :exports both
emacs --version
#+end_src

#+RESULTS:
: GNU Emacs 24.5.1
: Copyright (C) 2015 Free Software Foundation, Inc.
: GNU Emacs comes with ABSOLUTELY NO WARRANTY.
: You may redistribute copies of Emacs
: under the terms of the GNU General Public License.
: For more information about these matters, see the file named COPYING.

I'd say you want at least an emacs 24.4 (October 2014) or 24.5
(April 2015) to be out of troubles. Emacs 24.3 was released in March
2013, i.e., three years ago, which is quite old. 

Likewise, you'll want to check you have a recent version of org-mode:
#+begin_src sh :results output :exports both
emacs -batch --funcall "org-version" 2>&1 | grep version
#+end_src

#+RESULTS:
: Org-mode version 8.3.1 (8.3.1-dist @ /usr/share/emacs24/site-lisp/org-mode/)

The current latest version is actually 8.3.3 but you'll want at least
a version 8.2. 
** A stub of replicable article
Download the archive, untar it and simply make to generate the article. You should then be able to open the [[file:replicable/article.pdf][resulting article]].

#+begin_src sh :results output :exports both
wget -O replicable.tgz https://github.com/alegrand/RR_webinars/raw/master/1_replicable_article_laboratory_notebook/replicable/replicable.tgz
tar zxf replicable.tgz;
cd replicable
make 
evince article.pdf
#+end_src

If the =make= command fails (especially on Mac), it may be because emacs
or something else is not correctly installed. In that case, open the
article directly with the following command:
#+begin_src sh :results output :exports both
emacs -q --eval "(setq enable-local-eval t)" --eval "(setq enable-local-variables t)" \
	   --eval "(setq org-export-babel-evaluate t)" article.org
#+end_src
and export it to pdf with the following shortcut: =C-c C-e l o=

When you'll be tired of always reexecuting all the source code when
exporting, simply add the following line in the end of the [[file:replicable/article.org][article.org]]
document.
#+begin_src sh :results output :exports both
eval:    (setq org-export-babel-evaluate nil)
#+end_src
** Reproducible research emacs configuration for maintaining your laboratory notebook
*** Step 1: Prepare your journal
Create an =org/= directory in the top of your home:
#+begin_src sh :results output :exports both
cd ~
mkdir -p org/
#+end_src
Then copy [[https://raw.githubusercontent.com/alegrand/RR_webinars/master/1_replicable_article_laboratory_notebook/journal.org][this file]] in this =org/= directory. This file will be your
laboratory notebook and all the notes you will capture with =C-c c= (this
will be explained in the tutorial) will go automatically go in this
file. I populated the first entry of this notebook with many emacs
shortcuts that I will demonstrate.
*** Step 2: Set up Emacs configuration
- *Option 1* (if you're convinced and want my configuration for the rest
  of your life): Backup you own =.emacs= (who knows what may happen?) if
  you have one and replace it with the content of [[https://raw.githubusercontent.com/alegrand/RR_webinars/master/1_replicable_article_laboratory_notebook/init.el][this file]].
- *Option 2* (if you only want to give a try for today): Get [[https://raw.githubusercontent.com/alegrand/RR_webinars/master/1_replicable_article_laboratory_notebook/init.el][this file]]
  and launch emacs with this specific configuration with the following
  command:
  #+begin_src sh :results output :exports both
  emacs -q -l init.el
  #+end_src
*** Step 3: Check whether the installation is working or not
Open a new instance of Emacs and open a =foo.org= file. Copy in this
file the following:
   : #+begin_src sh :session foo :results output :exports both
   : ls -la
   : #+end_src

Put your cursor inside this code block and execute it with the
following command: =C-c C-c= (If you are not familiar with Emacs
commands, this one means '=Ctrl + C=' twice)

A Result block with the result of the command should appear if it
worked. 

In the tutorial we will show you the main features and shortcuts of
emacs/org-mode that will help you maintain your laboratory notebook
(the =journal.org=) and benefit from literate programming. The list of
features we will demonstrate is in the [[file:journal.org::*Emacs%20shortcuts][first entry of your labbook]].

